### ISSUE TITLE
Segmenting new labels 

### ISSUE THREAD

**Issue by devShaurya** [CubiCasa/CubiCasa5k#17]
Thanks for sharing your work.

I am able to parse the floor plan with the categories you have provided. However, I am working to parse other categories such as sofa, tables etc. I see the icons for these are present in the actual floorplans (like F1_original.png) but not included the model.svg.

Could you please provide a way to parse these icons as well?

**Comment by ccmarkus** [comment]
Sofa, tables etc labels do not exist since we have not collected that data in the first place.
Data in the model.svg contains only fixed furniture, so there are no other furniture items.
So you would need to label those yourself.

You could modify [labelme](https://github.com/wkentaro/labelme) for example and use that to label additional classes. Then just read the additional labels from secondary label file which has the additional labels you want. This would obviously need you to label them first.
